name: Mass Research
on:
  workflow_dispatch:
jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix-shell -p curl --run 'curl -s ifconfig.me > ip.txt'
      - uses: actions/upload-artifact@v4
        with:
          name: research-results
          path: ip.txt
